### ISSUE TITLE
No longer working in 1.4.8?

### ISSUE THREAD

**Issue by chris-c-thomas** [dfrankland/hyper-sync-settings#32]
I updated Hyper to the latest stable, 1.4.8, and no it seems to no longer be syncing to my Gist. My Gist is private (shouldn't be an issue) and I've tested this with a fresh install and new GitHub Token.

My ~/.hyper-plugins/.hyper-sync-settings.json

`{
  "personalAccessToken": "​2280...",
  "gistId": "3ba..."
}
`

So it's not a formatting error. Both of those are the valid token and ID. When I run Check for Updates, Backup Settings or Restore nothing happens. No errors in the console and 'Plugin hyper-sync-settings (2.0.2) loaded' appears.

**Comment by birkhofflee** [comment]
same here

**Comment by chris-c-thomas** [comment]
Reading the other issue it seems to be happening on both stable and beta channels of Hyper. Hopefully we can get a quick fix because I sync often but I'm unsure where to even look first.

**Comment by FezVrasta** [comment]
I get this error:

```
Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
```

**Comment by Dids** [comment]
I've found a workaround for now.  

1. Remove the broken repository:  
```bash
rm -fr ~/.hyper_plugins/.hyper-sync-settings
```
2. Recreate the repository:  
```bash
git clone git@gist.github.com:<GIST_ID>.git ~/.hyper_plugins/.hyper-sync-settings
```

That's all it takes. In fact, I don't think you'll need an access token for this either, as this way it'll be using your SSH keys directly.

The long term solution would be to either refactor the app to use git urls instead of https, or simply switch to the GitHub Gist API instead.

Either way, this solution seems to be working for now, but does require a bit of manual work.

**Comment by Dids** [comment]
Still looking in to the actual issue, and it seems to be related to creating the initial git repository under `.hyper-sync-settings`, not to the authentication etc.

I'll see if I can get a working PR going.

**Comment by sguergachi** [comment]
Can confirm doesn't work for me in same conditions

**Comment by okaufmann** [comment]
same here

**Comment by artemartemov** [comment]
any updates on this by any chance? the fix above works, however only for the first backup, the following backups fail unfortunately.

**Comment by sguergachi** [comment]
I had to manually copy paste the settings into the gist once and it seemed to sync after that.

**Comment by dfrankland** [comment]
Let's move this conversation over to #31 since Hyper 2.0 has been released.
