### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by weedgrease** [dfrankland/hyper-sync-settings#18]
```
bundle.js:661 Error: Cannot find module '/Users/kevin/.hyper_plugins/node_modules/hyper-sync-settings'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at paths.plugins.concat.map.err (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:659:20)
    at Array.map (native)
    at loadModules (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:652:54)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:757:1)
    at __webpack_require__ (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:20:30)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:50910:73)
```
Seems like it's not installing correctly but I've had similar issues with it finding a `nodegit` package as well. I haven't been able to launch this plugin successfully yet :/

**Comment by dfrankland** [comment]
`nodegit` will have issues until Hyper version `0.8.4` is released. More info can be found on issue #17

Also, `nodegit` probably won't work if you are using Node.js v7 at the moment because there are no pre-built images. This is a separate issue though.

As an intermediate fix, if you have Node.js@<7.0.0 copy the `.npmrc` file from this repo to `~/.hyper_plugins`, then run `npm i nodegit` in that directory.

**Comment by dfrankland** [comment]
If you are deadset on using Node.js@>=7.0.0, you'll need to let `nodegit` build from source. To do this, first you'll need to install `libgcrypt` like below:

```
brew install libgcrypt
```

Then you can continue to follow the instructions above:
>  As an intermediate fix, copy the `.npmrc` file from this repo to `~/.hyper_plugins`, then run `npm i nodegit` in that directory.

**Comment by weedgrease** [comment]
Thanks for the response - I've downgraded to 6.9.2 and started from scratch but still get the issue I pasted above. Nothing mentioned about nodegit anymore.

**Comment by dfrankland** [comment]
This should work now that Hyper v1.0.0 is released: https://github.com/zeit/hyper/releases/tag/1.0.0

Even if you are on Node v7.0.0 it will still work.

**Comment by dfrankland** [comment]
You may need to `rm -rf ~/.hyper_plugins/node_modules` and then force Hyper to re-download the dependencies.

**Comment by weedgrease** [comment]
```
bundle.js:669 Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kevin/.hyper_plugins/node_modules/nodegit/dist/nodegit.js:18:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

Getting this now after upgrading to 1.0.0, removing all installed packages and forcing a reinstall - should I follow your instructions above or were you expecting this to be solved with 1.0.0?

**Comment by dfrankland** [comment]
How did you go about forcing the re-install? Did you try to `npm install` or use "Update All Plugins" menu?

**Comment by weedgrease** [comment]
I used the `Update All Plugins` button

**Comment by dfrankland** [comment]
Hmmmm, this is a real head-scratcher. I am using Node v7.2.0 and Hyper v1.0.0, just blew up my `~/.hyper_plugins/node_modules` folder, and used `Update All Plugins` in the menu. It took a little while to re-install all my plugins, but everything worked really nicely afterwards.

Can you check that `nodegit` got installed? You could just do a quick:
```bash
ls -la ~/.hyper_plugins/node_modules/nodegit/package.json
```

**Comment by weedgrease** [comment]
Yep that file exists. I get an error notification saying "This plugin didn't self register" along with the stack trace above in the dev console.

**Comment by dfrankland** [comment]
Could you try the solution I've outlined here: https://github.com/dfrankland/hyper-sync-settings/issues/19#issuecomment-267415773

**Comment by weedgrease** [comment]
So I followed your instructions and I had already installed nodegit via brew, however, after getting the same error trace regarding nodegit, it suddenly just... worked. But now I'm getting a `settings not found` error, even though I opened the config from the Menubar & added the values to environment variables. Not sure what to do next. GitHub says the personal access token hasn't been used yet.

**Comment by dfrankland** [comment]
This should be all fixed by `hyper-sync-settings@2.0.0` with PR https://github.com/dfrankland/hyper-sync-settings/pull/23
